### ISSUE TITLE
Getting "Library call failed for SetAlpha()" error

### ISSUE THREAD

**Issue by nkmathew** [mattn/transparency-windows-vim#1]
![error](http://i.imgur.com/lWyhzyx.png)

Vim version:
![](http://i.imgur.com/OmlDoXU.png)

**Comment by mattn** [comment]
Fixed vimtweak.dll

**Comment by nkmathew** [comment]
Can you accomodate for cases where there are more than one vimtweak dlls in the runtime path e.g when I install mattn/vimtweak with Vundle while at the same time there being one in gvim.exe folder.
Doing a `globpath(&rtp, 'vimtweak.dll')` will return this(leading to the above error):

```
C:/Users/nkmathew/.vim/bundle/vimtweak/vimtweak.dll
C:/Program Files/Vim/vim74/vimtweak.dll
```

You could have something this in the plugin:

``` vim
let s:dll = split(globpath(&rtp, 'vimtweak.dll'), '\n')[0]
```

**Comment by mattn** [comment]
libcallnr which is a function to call dll from vim script, it open handle and close handle immediately after called function in dll. so afaik, it don't make issue, i think.

**Comment by nkmathew** [comment]
I meant it should handle the case where there are more than one vimtweak.dll files in runtime path

**Comment by mattn** [comment]
How about to below?

``` vim
let s:dll = get(g:, 'vimtweak_dll_path', globpath(&rtp, 'vimtweak.dll'))
```

possible to customize dll-paths.

**Comment by nkmathew** [comment]
Looks good
