### ISSUE TITLE
Error detected while processing function <SNR>53_Transparency

### ISSUE THREAD

**Issue by kalindu1** [mattn/transparency-windows-vim#4]
I get this Error when i open gvim. This plugin worked well before.

Error:
```
Error detected while processing function <SNR>53_Transparency:
E364: Library call failed for "SetAlpha()"

```

![Capture](https://user-images.githubusercontent.com/77789643/136205279-ee2e56bb-7f4c-435f-ad5c-c39cb5c694fe.PNG)

**Comment by mattn** [comment]
Did you put vimtweak.dll on your directory?

**Comment by kalindu1** [comment]
Yes I did put the vimtweak64.dll in the vim directory with gvim.

**Comment by mattn** [comment]
The location of the dll must be https://github.com/mattn/transparency-windows-vim#install

**Comment by kalindu1** [comment]
Are you telling me to put the vimtweak64.dll in the transparency-windows-vim folder?

**Comment by mattn** [comment]
Yes, or specify the location like this.

```
let g:vimtweak_dll_path = 'C:\path\to\the\vimtweak64.dll'
```

**Comment by kalindu1** [comment]
I added it to the folder but it still doesn't work
![trpw](https://user-images.githubusercontent.com/77789643/136421448-9fbbf8e6-2cbc-45fb-9443-ace36d63e930.PNG)
.

**Comment by kalindu1** [comment]
I even tried by putting one by one.

**Comment by kalindu1** [comment]
Where is that SetAlpha library located ?

**Comment by mattn** [comment]
Yes.

https://github.com/mattn/vimtweak/blob/67986ea092087a51196b938711947de09bc3d282/vimtweak.c#L62

**Comment by mattn** [comment]
What do you get with:

```
:echo get(split(globpath(&rtp, has('win64') ? 'vimtweak64.dll' : 'vimtweak32.dll'), '\n'), 0, '')
```

**Comment by kalindu1** [comment]
If you need you can find my vimrc in here https://github.com/kalindu1/Vimrc
It's a mess.

**Comment by kalindu1** [comment]
I got this
![1](https://user-images.githubusercontent.com/77789643/136425020-6d354020-768b-4bfa-847c-67b793d32754.PNG)

**Comment by mattn** [comment]
Your OS is 32bit Windows? Right?

**Comment by kalindu1** [comment]
Nope it's 64bit!

Se
![see](https://user-images.githubusercontent.com/77789643/136652663-38fb8f8b-103f-494b-9c8f-6a4870292449.PNG)

**Comment by kalindu1** [comment]
The plugin worked right after I installed it.
I had vimtweak installed before for a plugin called gvim_fullscreen_win32. So I had the vimtweak.dll in the vim folder.

**Comment by kalindu1** [comment]
vimtweak can't call for any libraries.

Like 
```
:call libcallnr("vimtweak64.dll", "SetAlpha", 200)
```
```
:call libcallnr("vimtweak64.dll", "EnableMaximize", 1)
```
```
:call libcallnr("vimtweak64.dll", "EnableTopMost", 1)
```

**Comment by kalindu1** [comment]
Why is it failing to load these libraries?

**Comment by kalindu1** [comment]
I installed the newest version of vim 8.2.3 and all is working now.
(I was using vim 8.2 for some reason it didn't work)
Thank you for everything!
